#默认使用配置
spring:
  profiles:
      active: dev

server:
  port: 8085

---

#开发配置
spring:
  profiles: dev
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.31.212:8849
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: survey
          uri: lb://survey
          predicates:
            - Path=/survey/**
#        - id: project
#          uri: lb://project
#          predicates:
#            - Path=/project/**
      globalcors:
        cors-configurations:
          '[/**]':
#            allowedOrigins: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            max-age: 360000
        add-to-simple-url-handler-mapping: true  # 解决option的跨域问题
      httpclient:
        connect-timeout: 20000
        response-timeout: 20s
#server:
#  netty:
#    connection-timeout: 10000